(()=>{const P=PB,B=P.B={};
B.new=(id,sid,level,seed)=>{P.W.keys={};P.scene='battle';B.encId=id;B.boss=id<0;B.final=B.boss&&sid===1&&level>P.cap;P.data.party.forEach(c=>{c.cd=[0,0,0,0];c.shield=0});B.active=0;B.entry=180;B.enemy=P.make(sid,level,0,0,seed);B.enemy.discord=B.enemy.discordMax=B.boss?30:20;if(B.boss){B.enemy.hp=B.enemy.hpMax+=B.final?26:12;B.enemy.pwr+=B.final?4:2}B.mode='menu';B.turn=0;B.hornReady=1;B.log=[`${B.final?'PRISM WARDEN':B.boss?'GUARDIAN '+P.spec[sid][0]:'WILD '+P.spec[sid][0]} APPEARS!`];B.pending=null;B.progress=[];B.bonus=0;B.win=B.captured=0;B.harmX=0;B.harmDir=1;B.evoT=0;B.seq=[];B.fx=0};
B.say=s=>{if(B.field)return P.W.note(s);B.log.push(s);if(B.log.length>14)B.log.shift()};B.cur=()=>P.data.party[B.active];B.spe=c=>P.spec[c.species];B.eff=(a,b)=>{let d=(a-b+6)%6;return d===5?1.5:d===1?.67:1};
/* Six-affinity cycle: attacker affinity a is strong (1.5x) vs a+1, weak (0.67x) vs a-1,
neutral otherwise (Solar>Tide>Grove>Moon>Volt>Ember>Solar). The Spectrum Warden's live
affinity is turn%6, so its offence and vulnerability both shift each turn. gPri is a per-
affinity preferred move index giving Guardians distinct move weighting from their own kit. */
B.aff=['SOLAR','TIDE','GROVE','MOON','VOLT','EMBER'];B.gPri=[3,1,2,2,3,3];
B.tAff=c=>B.final&&c===B.enemy?B.turn%6:P.spec[c.species][1];
B.aAff=(c,k)=>B.final&&c===B.enemy?B.turn%6:P.ma(k);
B.calc=(a,t,k,b=0)=>{let m=P.m(k),aa=B.aAff(a,k),eb=a!==B.enemy&&P.data.echoes>>aa&1?2:0;return Math.max(1,Math.round((a.pwr+m[0]+b+eb)*B.eff(aa,B.tAff(t))-t.grd*.55))};
B.hit=(a,t,k,b=0)=>{let mult=B.eff(B.aAff(a,k),B.tAff(t)),raw=B.calc(a,t,k,b),block=Math.min(t.shield||0,raw);t.shield=Math.max(0,(t.shield||0)-block);let d=raw-block;t.hp=Math.max(0,t.hp-d);return{d,block,mult}};
B.enemyPick=()=>{if(B.boss){let p=B.gPri[B.tAff(B.enemy)];if(!B.enemy.cd[p])return[1,0,p]}let order=[1,0,2,3],i=order[B.turn%4];if(B.enemy.cd[i])i=B.enemy.cd.findIndex(x=>!x);return[1,0,i<0?0:i]};
B.pri=q=>q[1]===1?2:q[1]===2?1:0;B.spd=q=>q[0]===0?B.cur().spd:B.enemy.spd;
B.begin=act=>{if(B.mode!=='menu')return;B.mode='busy';let enemy=B.enemyPick();B.seq=[act,enemy].sort((x,y)=>B.pri(y)-B.pri(x)||B.spd(y)-B.spd(x)||(x[0]===0?-1:1));setTimeout(B.resolveNext,120)};
B.move=i=>{if(B.mode!=='menu')return;let a=B.cur(),k=a.moves[i];if(k==null)return;if(a.cd[i])return B.say(`${P.mn[k]} is cooling down.`);B.begin([0,0,i])};
B.resolveNext=()=>{if(B.win)return;let q=B.seq.shift();if(!q)return B.endTurn();if(q[0]===0&&B.cur().hp<=0)return B.resolveNext();if(q[1]===0)B.useMove(q[0],q[2]);else if(q[1]===1)B.doShift(q[2]);else B.doHorn();setTimeout(()=>B.afterAction(q[0]),330)};
B.useMove=(side,i)=>{let a=side===0?B.cur():B.enemy,t=side===0?B.enemy:B.cur(),key=a.moves[i],m=P.m(key);if(!m)return;a.cd[i]=m[2]+1;if(m[3]){a.shield=(a.shield||0)+(side===0?6+(a.grd>>1):5+(a.grd>>2));P.s(310,.11,.7,1);return B.say(`${P.mn[key]}  SHIELD ${a.shield}`)}let bonus=side===0?B.bonus:0;if(side===0)B.bonus=0;let h=B.hit(a,t,key,bonus),aa=B.aAff(a,key),fx=h.mult>1?' SUPER!':h.mult<1?' RESISTED':'';B.fx=[side,300,aa,h.mult,h.block];if(h.mult>1)P.s(700,.07,2.2,1);P.s(side?150:230+aa*45,.09,side?.65:1.35,side);if(side===0){let dis=Math.round(m[1]*h.mult);B.enemy.discord=Math.max(0,B.enemy.discord-dis);B.say(`${P.mn[key]}  ${h.d} DMG  DISCORD -${dis}${fx}`)}else B.say(`${P.mn[key]}  ${h.d} DMG${fx}`)};
B.afterAction=side=>{if(B.enemy.hp<=0){B.seq=[];B.say(`${P.spec[B.enemy.species][0]} DISPERSED`);return setTimeout(()=>B.finish(false),360)}let a=B.cur();if(a.hp<=0){B.say(`${B.spe(a)[0]} DIMMED`);let live=P.data.party.filter((x,i)=>i!==B.active&&x.hp>0);if(!live.length){B.seq=[];return setTimeout(()=>B.finish(false,true),360)}B.bonus=0;B.seq=B.seq.filter(x=>x[0]!==0);if(live.length>1){B.mode='replace';return}B.active=P.data.party.indexOf(live[0]);B.say(`${B.spe(B.cur())[0]} ENTERS`)}B.resolveNext()};
B.endTurn=()=>{for(let c of [...P.data.party,B.enemy])c.cd=c.cd.map(x=>Math.max(0,x-1));B.turn++;if(B.final)B.say(`WARDEN → ${B.aff[B.turn%6]}`);B.mode='menu'};
B.openShift=()=>{if(B.mode==='menu'&&P.data.party.some((x,i)=>i!==B.active&&x.hp>0)){B.mode='shift'}};B.cancelShift=()=>{if(B.mode==='shift'){B.mode='menu'}};
B.shift=i=>{if(B.mode!=='shift'&&B.mode!=='replace'||i===B.active||!P.data.party[i]||P.data.party[i].hp<=0)return;if(B.mode==='replace'){B.active=i;B.mode='busy';B.say(`${B.spe(B.cur())[0]} ENTERS`);return B.resolveNext()}B.mode='menu';B.begin([0,1,i])};
B.rt=c=>c===10?'ATK+5':c===18?'SH+8':c===2?'HP+6':c===24?'SH+5 A+2':c===1?'SH+4':'ATK+2';B.doShift=i=>{let out=P.spec[B.cur().species][1];B.active=i;let inc=P.spec[B.cur().species][1],code=out*6+inc,a=B.cur(),name='SPECTRAL ECHO',text=B.rt(code);B.bonus=2;if(code===10){name='CONDUCTION';B.bonus=5}else if(code===18){name='ECLIPSE';a.shield+=8;B.bonus=0}else if(code===2){name='SUNSHOWER';a.hp=Math.min(a.hpMax,a.hp+6);B.bonus=0}else if(code===24){name='AURORA GUARD';a.shield+=5;B.bonus=2}else if(code===1){name='DAYBREAK MIST';a.shield+=4;B.bonus=0}B.say(`${name}  ${text}`)};
B.horn=()=>{if(B.mode!=='menu')return;let own=P.data.seen>>B.enemy.species&1;if(B.enemy.discord<=6&&!B.boss&&!own)return B.startHarm();if(!B.hornReady)return B.say(B.boss?'GUARDIAN CANNOT BIND':own?'ALREADY HARMONIZED':'PRISM PULSE SPENT');B.begin([0,2])};
B.doHorn=()=>{if(!B.hornReady)return;B.hornReady=0;let a=B.cur();a.hp=Math.min(a.hpMax,a.hp+7);a.cd=[0,0,0,0];P.s(420,.18,1.5,1);B.say('PRISM PULSE  RESTORED')};
B.startHarm=()=>{P.s(520,.14,1.7,1);B.mode='harm';B.harmX=8;B.harmDir=1;B.say('HARMONIZE  HIT THE BRIGHT BAND')};
B.tick=dt=>{if(B.fx&&(B.fx[1]-=dt)<0)B.fx=0;if(B.mode==='harm'){B.harmX+=B.harmDir*dt*.055;if(B.harmX>92){B.harmX=92;B.harmDir=-1}if(B.harmX<8){B.harmX=8;B.harmDir=1}}if(B.mode==='evo')B.evoT+=dt;if(B.entry>0)B.entry-=dt};
B.harmHit=()=>{if(B.mode!=='harm')return;let hp=B.enemy.hp/B.enemy.hpMax,wide=12+(1-hp)*10+(1-B.enemy.discord/B.enemy.discordMax)*10,ok=Math.abs(B.harmX-50)<=wide;B.mode='busy';if(ok){B.say(`${P.spec[B.enemy.species][0]} HARMONIZED!`);let q=P.make(B.enemy.species,B.enemy.level,B.enemy.moves,0,B.enemy.seed);B.joined=P.data.party.length<3;(B.joined?P.data.party:P.data.reserve).push(q);P.data.seen|=1<<q.species;if(q.level>=P.cap)P.data.master|=1<<q.species;P.s(540,.28,2,1);setTimeout(()=>B.finish(true),520)}else{B.enemy.discord=Math.min(B.enemy.discordMax,B.enemy.discord+4);P.s(240,.15,.55);B.say('MISSED  DISCORD RISES');B.seq=[B.enemyPick()];setTimeout(B.resolveNext,320)}};
B.finish=(captured,wiped=false)=>{B.seq=[];B.wiped=wiped;if(wiped){P.data.party.forEach(x=>x.hp=x.hpMax);B.win=2;B.mode='result';P.save(P.data);B.say('TEAM RESTORED AT SHRINE');return}B.win=captured?1:3;B.captured=captured?1:0;B.progress=[];P.data.party.forEach((c,i)=>B.gain(c,(i===B.active?40:24)*(B.boss?8:1)));P.save(P.data);B.nextProgress()};
B.gain=(c,n)=>{c.xp+=n;while(c.level<P.cap){let need=P.need(c.level);if(c.xp<need)break;c.xp-=need;let oldSpec=c.species,s=P.spec[oldSpec];c.level++;c.hpMax+=2;c.hp=c.hpMax;c.pwr++;if(!(c.level&1))c.grd++;B.progress.push([0,c,s[0],c.level]);if(s[8]===c.level&&s[9]>=0){let oldId=c.species,next=s[9],ratio=c.hp/c.hpMax,f=P.make(next,c.level,c.moves,c.xp,c.seed);P.data.master|=1<<oldId;P.data.seen|=1<<next;Object.assign(c,f);c.hp=Math.max(1,Math.round(c.hpMax*ratio));B.progress.push([1,c,oldId,next,s[0],P.spec[next][0]])}let learn=P.learn(c.species,c.level);if(learn>=0){if(c.moves.length<4){c.moves.push(learn);B.progress.push([2,c,learn])}else B.progress.push([3,c,learn])}if(c.level>=P.cap)P.data.master|=1<<c.species}};
B.nextProgress=()=>{B.pending=B.progress.shift()||null;if(!B.pending){if(B.field){let e=B.field>1;B.field=0;B.mode='menu';P.save(P.data);P.scene=e?'ending':'world';return}B.mode='result';P.save(P.data);B.say(B.captured?'FORM SAVED':'TRAINING COMPLETE');return}B.mode=B.pending[0]===1?'evo':B.pending[0]===3?'learn':'progress';B.evoT=0;if(B.pending[0]===1||B.pending[0]===0&&B.pending[3]>=P.cap)P.s(620+B.pending[0]*120,.3,1.8,1)};
B.advance=()=>{if(B.mode==='evo'&&B.evoT<820)return;if(B.mode!=='progress'&&B.mode!=='evo')return;B.pending=null;B.nextProgress()};
B.pickForget=i=>{let p=B.pending;if(!p||p[0]!==3)return;if(i<4){p[1].moves[i]=p[2];B.say(`${P.mn[p[2]]} LEARNED`)}else B.say('MOVE KEPT');P.save(P.data);B.pending=null;B.nextProgress()};
B.leave=()=>P.W.return(B.encId,B.wiped,B.win);
B.run=()=>{if(B.mode!=='menu'||B.boss)return;P.s(210,.1,.55);P.W.return(B.encId,0,0);P.W.note('GOT AWAY SAFELY')};

})();
